require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AuthenticationsController do

  def mock_authentication(stubs={})
    @mock_authentication ||= mock_model(Authentication, stubs).as_null_object
  end

  describe "GET index" do
    before(:each) do    
      login
    end
    
    it "should assign the current user's authentications as @authentications" do
      controller.current_user.should_receive(:authentications).and_return(mock_authentication)
      get :index
      assigns(:authentications).should eq(mock_authentication)
    end
  end
  
  describe "POST create" do    
    context "Existing user" do
      # FIXME: NEED TO WRITE THIS.
      pending 'NEED TO WRITE THIS.'
      # it "should set a flash message, sign the user in, and redirect to the user's page" do
      #   Authentication.should_receive(:where).and_return(mock_authentication)
      #   mock_authentication.should_receive(:user).and_return(@user)
      #   flash[:error].should == "You are now signed in."
      #   response.should redirect_to(@user)
      # end
    end
    
    context "New user" do
      # FIXME: NEED TO WRITE THIS.
      pending 'NEED TO WRITE THIS.'
    end
  end

end
