require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UsersController do

  before(:each) do
    login
  end

  describe 'GET show' do
    # FIXME: NEED TO WRITE THIS.
    it "should set the user's info" do
      get :show, :id => @user.id
      assigns(:user).should == @user
      response.should be_success
    end
  end
end
